#!/bin/sh
set -e
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
cd $DIR

build=../build/ios
build_headers=$build/headers

rm -rf $build
mkdir -p $build
mkdir -p $build_headers

soomla-native/projects/cocos2dx-ios-levelup/build_all

cp -R soomla-native/projects/cocos2dx-ios-levelup/build/* $build/

cp -L submodules/ios-levelup/build/libSoomlaiOSLevelUp.a $build/
cp -RL submodules/ios-levelup/build/headers/SoomlaiOSLevelUp $build_headers/

cd - > /dev/null
