#!/bin/sh
set -e
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
cd $DIR

build=../build/android

rm -rf $build
mkdir -p $build

soomla-native/projects/cocos2dx-android-levelup/build_all

# handle special case of build_all location for android-levelup
cp -L submodules/android-levelup/build/AndroidLevelUp.jar $build/
cp -R soomla-native/projects/cocos2dx-android-levelup/build/* $build/

cd - > /dev/null
