//
// Created by Shubin Fedor on 22/08/14.
// Copyright (c) 2014 SOOMLA. All rights reserved.
//


#ifndef __CCWorld_H_
#define __CCWorld_H_

#include "CCSoomlaEntity.h"
#include "CCGate.h"
#include "CCScore.h"
#include "CCMission.h"
#include "CCReward.h"

namespace soomla {

    class CCWorld: public CCSoomlaEntity {
        CC_SYNTHESIZE_RETAIN(CCGate *, mGate, Gate);
        CC_SYNTHESIZE_RETAIN(cocos2d::CCDictionary *, mInnerWorldsMap, InnerWorldsMap);
        CC_SYNTHESIZE_RETAIN(cocos2d::CCDictionary *, mScores, Scores);
        CC_SYNTHESIZE_RETAIN(cocos2d::CCArray*, mMissions, Missions);
    public:
        CCWorld(): CCSoomlaEntity(), mGate(NULL), mInnerWorldsMap(NULL), mScores(NULL), mMissions(NULL) {
        }

        static CCWorld *create(cocos2d::CCString *id);
        static CCWorld *create(cocos2d::CCString *id, CCGate *gate,
                cocos2d::CCDictionary *innerWorldsMap, cocos2d::CCDictionary *scores, cocos2d::CCArray *missions);

        SL_CREATE_WITH_DICTIONARY(CCWorld);

        virtual bool init(cocos2d::CCString *id);
        virtual bool init(cocos2d::CCString *id, CCGate *gate,
                cocos2d::CCDictionary *innerWorldsMap, cocos2d::CCDictionary *scores, cocos2d::CCArray *missions);

        virtual bool initWithDictionary(cocos2d::CCDictionary* dict);

        virtual cocos2d::CCDictionary *toDictionary();

        virtual char const *getType() const;

        virtual ~CCWorld();

    public:
        void addInnerWorld(CCWorld *world);
        void addMission(CCMission *mission);
        void addScore(CCScore *score);
        
        CCWorld *getInnerWorldAt(int index);

        void batchAddLevelsWithTemplates(int numLevels, CCGate *gateTemplate, CCScore *scoreTemplate, CCMission *missionTemplate);
        void batchAddLevelsWithTemplates(int numLevels, CCGate *gateTemplate, cocos2d::CCArray *scoreTemplates, cocos2d::CCArray *missionTemplates);
        void batchAddDependentLevelsWithTemplates(int numLevels, CCScore *scoreTemplate, CCMission *missionTemplate);
        void batchAddDependentLevelsWithTemplates(int numLevels, cocos2d::CCArray *scoreTemplates, cocos2d::CCArray *missionTemplates);

        void setSingleScoreValue(double amount);
        void decSingleScore(double amount);
        void incSingleScore(double amount);
        CCScore *getSingleScore();

        void resetScores(bool save);
        void decScore(char const *scoreId, double amount);
        void incScore(char const *scoreId, double amount);

        cocos2d::CCDictionary *getRecordScores();
        cocos2d::CCDictionary *getLatestScores();

        void setScoreValue(char const *id, double scoreVal);
        void setScoreValue(char const *id, double scoreVal, bool onlyIfBetter);

        bool isCompleted();
        virtual void setCompleted(bool completed);
        virtual void setCompleted(bool completed, bool recursive);

        void assignReward(CCReward *reward);
        cocos2d::CCString *getAssignedRewardId();

        bool canStart();
    private:
        char const *getIdForAutoGeneratedLevel(char const *id, int idx);
        char const *getIdForAutoGeneratedScore(char const *id, int idx);
        char const *getIdForAutoGeneratedGate(char const *id);
        char const *getIdForAutoGeneratedCompleteGate(char const *id, char const *previousId);
        char const *getIdForAutoGeneratedMission(char const *id, int idx);

        double sumInnerWorldsRecords();
        void createAddAutoLevel(const char *id, CCLevel *target, CCGate *targetGate, cocos2d::CCArray *scoreTemplates, cocos2d::CCArray *missionTemplates);
    };
}

#endif //__CCWorld_H_
